name: Send Code Coverage Report to Coveralls

# - run tests
# - forward report to coveralls

on:
  push:
    branches: master

jobs:
  build:
    environment: github-action-code-coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
        cache: 'npm'

    - run: npm ci
    - run: npm run test:coverage:report
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        COVERALLS_GIT_BRANCH: ${{ vars.COVERALLS_GIT_BRANCH }}
